version: '3.8'

services:
  gtfy-listener:
    build:
      context: /opt/gtfy-listener
      dockerfile: Dockerfile
    image: gtfy-listener
    container_name: gtfy-listener
    restart: unless-stopped
    environment:
      - GOTIFY_HOST=${GOTIFY_HOST:-gotify.example.com}
      - GOTIFY_TOKEN=${GOTIFY_TOKEN:-mytoken}
      - NTFY_HOST=${NTFY_HOST:-https://ntfy.example.com/mytopic}
      # Optional token support
      #- NTFY_TOKEN=${NTFY_TOKEN}
    depends_on:
      - gotify-server
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  gotify-server:
    image: gotify/server
    container_name: gotify-server
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - GOTIFY_SERVER_TRUSTEDPROXIES=[127.0.0.1]
      - GOTIFY_REGISTRATION=false
      - GOTIFY_SERVER_CORS_ALLOWHEADERS=[X-Gotify-Key, Authorization]
    volumes:
      - ./gotify/data:/app/data
    ports:
      - "8080:80"
